apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-main-svc
spec:
  type: NodePort
  selector:
    app: complete-prodcution-e2e-main-app
  ports:
    - port: 80
      targetPort: 8080